Algoritmo "contar até 20"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/02/2023
Var
// Seção de Declarações das variáveis 
num: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
num <-20
repita
escreval(num)
num<-num-2
ate (num <2)
escreval ("fim da contagem ...")
Fimalgoritmo