Algoritmo "semnome"
// solicitar dois números para o usuário
// e mostrar s soma entre eles

// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 

n1, n2: inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor: ")
leia(n1)

escreva("digite outro valor: ")
leia(n2)

soma<- n1+n2





Fimalgoritmo