Algoritmo "divisão"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 
n1, n2, Divi: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("informe um número: ")
leia(n1)
escreva("informe outro número: ")
leia(n2)

divi<- n1\n2
escrevaL("A divisão de ", n1," e", n2," é:" , divi)
Fimalgoritmo