Algoritmo "dobro"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 
n1:real
dob:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("informe um número: ")
leia(n1)
dob<-(n1)*2

escreval("o dobro número é:" , dob)

Fimalgoritmo