Algoritmo "imc"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/01/2023
Var
// Seção de Declarações das variáveis 
 peso, altura , imc :real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("qual seu peso: ")
leia(peso)

escreva("qual a sua altura: ")
leia(altura)

imc<- peso / altura ^ 2

escreva(" seu imc é : ", imc )

Fimalgoritmo
