Algoritmo "numero par"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/01/2023
Var
// Seção de Declarações das variáveis 
num: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("informe um número: ")
leia(num)

  se num % 2 = 0 entao
     escreva("o número é par!")
  fimse
Fimalgoritmo