Algoritmo "somatória"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/02/2023
Var
// Seção de Declarações das variáveis 
soma , cont , num : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma <-0

para cont <-1 ate 5 faca
escreval("entre com um valor: ")
leia(num)
soma <-soma+num
fimpara

escreval("a somatória dos valores: " , soma)
Fimalgoritmo