Algoritmo "tabuada do até 1 até 5"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/02/2023
Var
// Seção de Declarações das variáveis 
 cont , num , tab : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para cont <- 1 ate 5 faca
para num <-1 ate 10 faca
escreval (cont , " x " , num , " = " , tab )
tab <- cont * num
fimpara
escreval("")
fimpara

Fimalgoritmo